name: NLP
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=1.2.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=openblas
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37ha12b0ac_0
  - cycler=0.10.0=py37_0
  - cymem=2.0.2=py37h04f5b5a_0
  - cytoolz=0.9.0.1=py37h1de35cc_1
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.2.9=py37_0
  - entrypoints=0.3=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - idna=2.8=py37_0
  - importlib_metadata=1.1.0=py37_0
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.10.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libopenblas=0.3.6=hdc02c5d_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - more-itertools=7.2.0=py37_0
  - msgpack-numpy=0.4.3.2=py37_0
  - msgpack-python=0.6.1=py37h04f5b5a_1
  - murmurhash=1.0.2=py37h0a44026_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py37_0
  - numpy=1.17.4=py37hfd23ef0_0
  - numpy-base=1.17.4=py37ha711998_0
  - openssl=1.1.1d=h1de35cc_3
  - pandas=0.25.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - plac=0.9.6=py37_0
  - preshed=2.0.1=py37h0a44026_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pymongo=3.7.2=py37h0a44026_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyrsistent=0.15.6=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - readline=7.0=h1de35cc_5
  - regex=2019.11.1=py37h1de35cc_0
  - requests=2.22.0=py37_1
  - scipy=1.3.1=py37h1a1e112_0
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - spacy=2.0.16=py37h6440ff4_0
  - sqlite=3.30.1=ha441bb4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - thinc=6.12.1=py37hebd9d1a_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h1de35cc_0
  - tqdm=4.40.0=py_0
  - traitlets=4.3.3=py37_0
  - ujson=1.35=py37h1de35cc_0
  - urllib3=1.25.7=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - wrapt=1.10.11=py37h1de35cc_2
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - arxiv==0.5.1
    - dnspython==1.16.0
    - en-core-web-sm==2.0.0
    - feedparser==5.2.1
    - imbalanced-learn==0.6.1
    - nltk==3.4.5
    - pillow==6.2.1
    - pytest-runner==5.2
    - scikit-learn==0.22
    - wordcloud==1.6.0
prefix: /Users/mukeharmon/miniconda/envs/NLP

